using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.GamerServices;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Media;

namespace RTS {
    class Textures {
        public static Texture2D selectionTile;
        public static Texture2D humanBarUp;
        public static Texture2D humanBar;
        public static Texture2D humanCursor;
        public static Texture2D bound;
        public static Texture2D grass;
        public static Texture2D grass11;
        public static Texture2D dirt;
        public static Texture2D dirt200;
        public static Texture2D forest;
        public static Texture2D dirt2grass;
        public static Texture2D dirt2grass2;
        public static Texture2D dirt8grass;
        public static Texture2D dirt8grass2;
        public static Texture2D dirt4grass;
        public static Texture2D dirt4grass2;
        public static Texture2D dirt6grass;
        public static Texture2D dirt6grass2;
        public static Texture2D dirt286;
        public static Texture2D dirt284;
        public static Texture2D dirt224;
        public static Texture2D dirt226;
        public static Texture2D dirt27;
        public static Texture2D dirt29;
        public static Texture2D dirt21;
        public static Texture2D dirt23;
        public static Texture2D dirt19;
        public static Texture2D dirt37;
        public static Texture2D forest1;
        public static Texture2D forest2;
        public static Texture2D forest3;
        public static Texture2D forest4;
        public static Texture2D forest5;
        public static Texture2D forest6;
        public static Texture2D forest7;
        public static Texture2D forest8;
        public static Texture2D forest9;
        public static Texture2D forest24;
        public static Texture2D forest26;
        public static Texture2D forest84;
        public static Texture2D forest86;
        public static Texture2D water;
        public static Texture2D water1;
        public static Texture2D water2;
        public static Texture2D water3;
        public static Texture2D water4;
        public static Texture2D water5;
        public static Texture2D water6;
        public static Texture2D water7;
        public static Texture2D water8;
        public static Texture2D water9;
        public static Texture2D water24;
        public static Texture2D water26;
        public static Texture2D water84;
        public static Texture2D water86;
        public static Texture2D footmanIdle1;
        public static Texture2D footmanIdle1Sel;
        public static Texture2D footmanIdle2;
        public static Texture2D footmanIdle2Sel;
        public static Texture2D footmanIdle3;
        public static Texture2D footmanIdle3Sel;
        public static Texture2D footmanIdle4;
        public static Texture2D footmanIdle4Sel;
        public static Texture2D footmanIdle6;
        public static Texture2D footmanIdle6Sel;
        public static Texture2D footmanIdle7;
        public static Texture2D footmanIdle7Sel;
        public static Texture2D footmanIdle8;
        public static Texture2D footmanIdle8Sel;
        public static Texture2D footmanIdle9;
        public static Texture2D footmanIdle9Sel;
        public static Texture2D footmanMoving1A;
        public static Texture2D footmanMoving1B;
        public static Texture2D footmanMoving1C;
        public static Texture2D footmanMoving1D;
        public static Texture2D footmanMoving1ASel;
        public static Texture2D footmanMoving1BSel;
        public static Texture2D footmanMoving1CSel;
        public static Texture2D footmanMoving1DSel;
        public static Texture2D footmanMoving2A;
        public static Texture2D footmanMoving2B;
        public static Texture2D footmanMoving2C;
        public static Texture2D footmanMoving2D;
        public static Texture2D footmanMoving2ASel;
        public static Texture2D footmanMoving2BSel;
        public static Texture2D footmanMoving2CSel;
        public static Texture2D footmanMoving2DSel;
        public static Texture2D footmanMoving3A;
        public static Texture2D footmanMoving3B;
        public static Texture2D footmanMoving3C;
        public static Texture2D footmanMoving3D;
        public static Texture2D footmanMoving3ASel;
        public static Texture2D footmanMoving3BSel;
        public static Texture2D footmanMoving3CSel;
        public static Texture2D footmanMoving3DSel;
        public static Texture2D footmanMoving4A;
        public static Texture2D footmanMoving4B;
        public static Texture2D footmanMoving4C;
        public static Texture2D footmanMoving4D;
        public static Texture2D footmanMoving4ASel;
        public static Texture2D footmanMoving4BSel;
        public static Texture2D footmanMoving4CSel;
        public static Texture2D footmanMoving4DSel;
        public static Texture2D footmanMoving6A;
        public static Texture2D footmanMoving6B;
        public static Texture2D footmanMoving6C;
        public static Texture2D footmanMoving6D;
        public static Texture2D footmanMoving6ASel;
        public static Texture2D footmanMoving6BSel;
        public static Texture2D footmanMoving6CSel;
        public static Texture2D footmanMoving6DSel;
        public static Texture2D footmanMoving7A;
        public static Texture2D footmanMoving7B;
        public static Texture2D footmanMoving7C;
        public static Texture2D footmanMoving7D;
        public static Texture2D footmanMoving7ASel;
        public static Texture2D footmanMoving7BSel;
        public static Texture2D footmanMoving7CSel;
        public static Texture2D footmanMoving7DSel;
        public static Texture2D footmanMoving8A;
        public static Texture2D footmanMoving8B;
        public static Texture2D footmanMoving8C;
        public static Texture2D footmanMoving8D;
        public static Texture2D footmanMoving8ASel;
        public static Texture2D footmanMoving8BSel;
        public static Texture2D footmanMoving8CSel;
        public static Texture2D footmanMoving8DSel;
        public static Texture2D footmanMoving9A;
        public static Texture2D footmanMoving9B;
        public static Texture2D footmanMoving9C;
        public static Texture2D footmanMoving9D;
        public static Texture2D footmanMoving9ASel;
        public static Texture2D footmanMoving9BSel;
        public static Texture2D footmanMoving9CSel;
        public static Texture2D footmanMoving9DSel;
        
        public static Texture2D redStartLocation;
        public static Texture2D fog;
    }
}
